#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."

# Evaluate checkpoints generated by run_design_matrix_*.sh with their default
# split sizes. Override counts below if training used a different split.
CLIP_ARGS=()
if [[ -n "${CLIP_PRETRAINED:-}" ]]; then
  CLIP_ARGS=(--clip-pretrained "$CLIP_PRETRAINED")
fi

evaluate_dataset() {
  local dataset=$1 result_dir=$2 prefix=$3 query_num=$4 train_num=$5
  local suffix tag model_path
  for suffix in A_basic AB_triview AC_cbce ABC_all; do
    tag="${prefix}_${suffix}"
    model_path=$(find "$result_dir" -path "*${tag}*/model_best.pth" -printf '%T@ %p\n' 2>/dev/null | sort -nr | head -n 1 | cut -d' ' -f2- || true)
    if [[ -z "$model_path" ]]; then
      echo "[SKIP] No checkpoint for $dataset / $tag"
      continue
    fi
    MODEL_ARGS=(--disable-recon)
    if [[ "$suffix" == A_basic || "$suffix" == AC_cbce ]]; then
      MODEL_ARGS+=(--disable-fuse-mamba --disable-prompt)
    fi
    python main.py --dataset "$dataset" --caption-file caption.txt \
      --pretrained "$model_path" --query-num "$query_num" --train-num "$train_num" \
      --seed 42 --k-bits-list 32,64,128 --result-name results --exp-tag "$tag" \
      "${MODEL_ARGS[@]}" "${CLIP_ARGS[@]}"
  done
}

evaluate_dataset odir result/Result_TriPAH_ODIR odir "${ODIR_QUERY_NUM:-351}" "${ODIR_TRAIN_NUM:-2275}"
evaluate_dataset iu-xray result/Result_TriPAH_IUXray iux "${IUXRAY_QUERY_NUM:-380}" "${IUXRAY_TRAIN_NUM:-2500}"
evaluate_dataset mimic-cxr result/Result_TriPAH_MIMIC mimic "${MIMIC_QUERY_NUM:-10000}" "${MIMIC_TRAIN_NUM:-58141}"
